/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SiteRouteImport } from './routes/site'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiteIndexRouteImport } from './routes/site/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as SiteTtftRouteImport } from './routes/site/ttft'
import { Route as SettingsModelsRouteImport } from './routes/settings/models'
import { Route as SettingsKeyboardRouteImport } from './routes/settings/keyboard'
import { Route as SettingsHistoryRouteImport } from './routes/settings/history'
import { Route as SettingsCustomizationRouteImport } from './routes/settings/customization'
import { Route as SettingsContactRouteImport } from './routes/settings/contact'
import { Route as SettingsAttachmentsRouteImport } from './routes/settings/attachments'
import { Route as SettingsApiKeysRouteImport } from './routes/settings/api-keys'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as ChatThreadIdRouteImport } from './routes/chat/$threadId'
import { Route as ApiTranscribeIndexRouteImport } from './routes/api/transcribe/index'
import { Route as ApiSearchIndexRouteImport } from './routes/api/search/index'
import { Route as ApiChatIndexRouteImport } from './routes/api/chat/index'
import { Route as ApiImageGenerateRouteImport } from './routes/api/image/generate'
import { Route as ApiChatStreamRouteImport } from './routes/api/chat/stream'
import { Route as ApiChatStopRouteImport } from './routes/api/chat/stop'
import { Route as ApiChatSearchRouteImport } from './routes/api/chat/search'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SiteTtftRoute = SiteTtftRouteImport.update({
  id: '/ttft',
  path: '/ttft',
  getParentRoute: () => SiteRoute,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsKeyboardRoute = SettingsKeyboardRouteImport.update({
  id: '/keyboard',
  path: '/keyboard',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsHistoryRoute = SettingsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCustomizationRoute = SettingsCustomizationRouteImport.update({
  id: '/customization',
  path: '/customization',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsContactRoute = SettingsContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAttachmentsRoute = SettingsAttachmentsRouteImport.update({
  id: '/attachments',
  path: '/attachments',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ApiTranscribeIndexRoute = ApiTranscribeIndexRouteImport.update({
  id: '/api/transcribe/',
  path: '/api/transcribe/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchIndexRoute = ApiSearchIndexRouteImport.update({
  id: '/api/search/',
  path: '/api/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatIndexRoute = ApiChatIndexRouteImport.update({
  id: '/api/chat/',
  path: '/api/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageGenerateRoute = ApiImageGenerateRouteImport.update({
  id: '/api/image/generate',
  path: '/api/image/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatStreamRoute = ApiChatStreamRouteImport.update({
  id: '/api/chat/stream',
  path: '/api/chat/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatStopRoute = ApiChatStopRouteImport.update({
  id: '/api/chat/stop',
  path: '/api/chat/stop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatSearchRoute = ApiChatSearchRouteImport.update({
  id: '/api/chat/search',
  path: '/api/chat/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/site': typeof SiteRouteWithChildren
  '/studio': typeof StudioRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/contact': typeof SettingsContactRoute
  '/settings/customization': typeof SettingsCustomizationRoute
  '/settings/history': typeof SettingsHistoryRoute
  '/settings/keyboard': typeof SettingsKeyboardRoute
  '/settings/models': typeof SettingsModelsRoute
  '/site/ttft': typeof SiteTtftRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/site/': typeof SiteIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/search': typeof ApiChatSearchRoute
  '/api/chat/stop': typeof ApiChatStopRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/api/image/generate': typeof ApiImageGenerateRoute
  '/api/chat/': typeof ApiChatIndexRoute
  '/api/search/': typeof ApiSearchIndexRoute
  '/api/transcribe/': typeof ApiTranscribeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/studio': typeof StudioRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/contact': typeof SettingsContactRoute
  '/settings/customization': typeof SettingsCustomizationRoute
  '/settings/history': typeof SettingsHistoryRoute
  '/settings/keyboard': typeof SettingsKeyboardRoute
  '/settings/models': typeof SettingsModelsRoute
  '/site/ttft': typeof SiteTtftRoute
  '/chat': typeof ChatIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/site': typeof SiteIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/search': typeof ApiChatSearchRoute
  '/api/chat/stop': typeof ApiChatStopRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/api/image/generate': typeof ApiImageGenerateRoute
  '/api/chat': typeof ApiChatIndexRoute
  '/api/search': typeof ApiSearchIndexRoute
  '/api/transcribe': typeof ApiTranscribeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/site': typeof SiteRouteWithChildren
  '/studio': typeof StudioRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/contact': typeof SettingsContactRoute
  '/settings/customization': typeof SettingsCustomizationRoute
  '/settings/history': typeof SettingsHistoryRoute
  '/settings/keyboard': typeof SettingsKeyboardRoute
  '/settings/models': typeof SettingsModelsRoute
  '/site/ttft': typeof SiteTtftRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/site/': typeof SiteIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/search': typeof ApiChatSearchRoute
  '/api/chat/stop': typeof ApiChatStopRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/api/image/generate': typeof ApiImageGenerateRoute
  '/api/chat/': typeof ApiChatIndexRoute
  '/api/search/': typeof ApiSearchIndexRoute
  '/api/transcribe/': typeof ApiTranscribeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chat'
    | '/settings'
    | '/site'
    | '/studio'
    | '/chat/$threadId'
    | '/settings/account'
    | '/settings/api-keys'
    | '/settings/attachments'
    | '/settings/contact'
    | '/settings/customization'
    | '/settings/history'
    | '/settings/keyboard'
    | '/settings/models'
    | '/site/ttft'
    | '/chat/'
    | '/settings/'
    | '/site/'
    | '/api/auth/$'
    | '/api/chat/search'
    | '/api/chat/stop'
    | '/api/chat/stream'
    | '/api/image/generate'
    | '/api/chat/'
    | '/api/search/'
    | '/api/transcribe/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/studio'
    | '/chat/$threadId'
    | '/settings/account'
    | '/settings/api-keys'
    | '/settings/attachments'
    | '/settings/contact'
    | '/settings/customization'
    | '/settings/history'
    | '/settings/keyboard'
    | '/settings/models'
    | '/site/ttft'
    | '/chat'
    | '/settings'
    | '/site'
    | '/api/auth/$'
    | '/api/chat/search'
    | '/api/chat/stop'
    | '/api/chat/stream'
    | '/api/image/generate'
    | '/api/chat'
    | '/api/search'
    | '/api/transcribe'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chat'
    | '/settings'
    | '/site'
    | '/studio'
    | '/chat/$threadId'
    | '/settings/account'
    | '/settings/api-keys'
    | '/settings/attachments'
    | '/settings/contact'
    | '/settings/customization'
    | '/settings/history'
    | '/settings/keyboard'
    | '/settings/models'
    | '/site/ttft'
    | '/chat/'
    | '/settings/'
    | '/site/'
    | '/api/auth/$'
    | '/api/chat/search'
    | '/api/chat/stop'
    | '/api/chat/stream'
    | '/api/image/generate'
    | '/api/chat/'
    | '/api/search/'
    | '/api/transcribe/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChatRoute: typeof ChatRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  StudioRoute: typeof StudioRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChatSearchRoute: typeof ApiChatSearchRoute
  ApiChatStopRoute: typeof ApiChatStopRoute
  ApiChatStreamRoute: typeof ApiChatStreamRoute
  ApiImageGenerateRoute: typeof ApiImageGenerateRoute
  ApiChatIndexRoute: typeof ApiChatIndexRoute
  ApiSearchIndexRoute: typeof ApiSearchIndexRoute
  ApiTranscribeIndexRoute: typeof ApiTranscribeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/': {
      id: '/site/'
      path: '/'
      fullPath: '/site/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/site/ttft': {
      id: '/site/ttft'
      path: '/ttft'
      fullPath: '/site/ttft'
      preLoaderRoute: typeof SiteTtftRouteImport
      parentRoute: typeof SiteRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/keyboard': {
      id: '/settings/keyboard'
      path: '/keyboard'
      fullPath: '/settings/keyboard'
      preLoaderRoute: typeof SettingsKeyboardRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/history': {
      id: '/settings/history'
      path: '/history'
      fullPath: '/settings/history'
      preLoaderRoute: typeof SettingsHistoryRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/customization': {
      id: '/settings/customization'
      path: '/customization'
      fullPath: '/settings/customization'
      preLoaderRoute: typeof SettingsCustomizationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/contact': {
      id: '/settings/contact'
      path: '/contact'
      fullPath: '/settings/contact'
      preLoaderRoute: typeof SettingsContactRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/attachments': {
      id: '/settings/attachments'
      path: '/attachments'
      fullPath: '/settings/attachments'
      preLoaderRoute: typeof SettingsAttachmentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/api/transcribe/': {
      id: '/api/transcribe/'
      path: '/api/transcribe'
      fullPath: '/api/transcribe/'
      preLoaderRoute: typeof ApiTranscribeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search/': {
      id: '/api/search/'
      path: '/api/search'
      fullPath: '/api/search/'
      preLoaderRoute: typeof ApiSearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/': {
      id: '/api/chat/'
      path: '/api/chat'
      fullPath: '/api/chat/'
      preLoaderRoute: typeof ApiChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image/generate': {
      id: '/api/image/generate'
      path: '/api/image/generate'
      fullPath: '/api/image/generate'
      preLoaderRoute: typeof ApiImageGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/stream': {
      id: '/api/chat/stream'
      path: '/api/chat/stream'
      fullPath: '/api/chat/stream'
      preLoaderRoute: typeof ApiChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/stop': {
      id: '/api/chat/stop'
      path: '/api/chat/stop'
      fullPath: '/api/chat/stop'
      preLoaderRoute: typeof ApiChatStopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/search': {
      id: '/api/chat/search'
      path: '/api/chat/search'
      fullPath: '/api/chat/search'
      preLoaderRoute: typeof ApiChatSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsAttachmentsRoute: typeof SettingsAttachmentsRoute
  SettingsContactRoute: typeof SettingsContactRoute
  SettingsCustomizationRoute: typeof SettingsCustomizationRoute
  SettingsHistoryRoute: typeof SettingsHistoryRoute
  SettingsKeyboardRoute: typeof SettingsKeyboardRoute
  SettingsModelsRoute: typeof SettingsModelsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsAttachmentsRoute: SettingsAttachmentsRoute,
  SettingsContactRoute: SettingsContactRoute,
  SettingsCustomizationRoute: SettingsCustomizationRoute,
  SettingsHistoryRoute: SettingsHistoryRoute,
  SettingsKeyboardRoute: SettingsKeyboardRoute,
  SettingsModelsRoute: SettingsModelsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface SiteRouteChildren {
  SiteTtftRoute: typeof SiteTtftRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteTtftRoute: SiteTtftRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChatRoute: ChatRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  StudioRoute: StudioRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChatSearchRoute: ApiChatSearchRoute,
  ApiChatStopRoute: ApiChatStopRoute,
  ApiChatStreamRoute: ApiChatStreamRoute,
  ApiImageGenerateRoute: ApiImageGenerateRoute,
  ApiChatIndexRoute: ApiChatIndexRoute,
  ApiSearchIndexRoute: ApiSearchIndexRoute,
  ApiTranscribeIndexRoute: ApiTranscribeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
